binsync/binsync

- binsync/client.py
- binsync/state.py
- plugins/ida_binsync/ida_binsync/controller.py
- plugins/ida_binsync/ida_binsync/sync_menu.py
> added sync_all basic functionality

- plugins/binja_binsync/control_panel.py
- plugins/ida_binsync/ida_binsync/controller.py
- plugins/ida_binsync/ida_binsync/plugin.py
- plugins/ida_binsync/ida_binsync/ui/info_panel.py
- plugins/ida_binsync/ida_binsync/ui/info_tables/func_info_table.py
- plugins/ida_binsync/ida_binsync/ui/info_tables/struct_info_table.py
- updated the info panel
- added more versatility for showing struct changes in the future.
> Refactor: Made a more updated and versatile info panel

- binsync/client.py
- binsync/data/comment.py
- binsync/data/stack_variable.py
- binsync/merge.py
- binsync/state.py
- plugins/ida_binsync/ida_binsync/compat.py
- plugins/ida_binsync/ida_binsync/controller.py
- plugins/ida_binsync/ida_binsync/hooks.py
- plugins/ida_binsync/ida_binsync/ui/info_panel.py
- added a better interface for commenting
- requires comments to now specify if decompiled or not and from what function
- fixed ida commenting in decompilation
- added initial merging code, which is not yet used.
> Feat: Better Commenting

- binsync/__init__.py
- binsync/client.py
- plugins/ida_binsync/ida_binsync/compat.py
- plugins/ida_binsync/ida_binsync/controller.py
- plugins/ida_binsync/ida_binsync/ui/config_dialog.py
- plugins/ida_binsync/ida_binsync/ui/info_panel.py
- Bring back the hash check by @rhelmot 
- Make branch checking compatible with non-remote git repos again
- Make status strings more readable
> Refactor of core and IDA

- plugins/ida_binsync/ida_binsync/ui/sync_menu.py
Make the naming convention less confusing on first glance, add ability to change these on the fly without hardcoded strings.
> Ida UI text refactor

- plugins/ida_binsync/ida_binsync/compat.py
- plugins/ida_binsync/ida_binsync/controller.py
- plugins/ida_binsync/ida_binsync/hooks.py
- plugins/ida_binsync/ida_binsync/ui/sync_menu.py
- scripts/launch_and_update_ida.sh
Still a work in progress.
End result:
Support structs with custom types
Support syncing re-typing of stack variables to both native types and custom types
> [WIP] Feat: IDA support for full type syncing

- binsync/__init__.py
- binsync/client.py
- binsync/data/comment.py
- binsync/data/func.py
- binsync/data/patch.py
- binsync/data/stack_variable.py
- binsync/data/struct.py
- binsync/data/user.py
- binsync/state.py
- plugins/ida_binsync/ida_binsync/compat.py
- plugins/ida_binsync/ida_binsync/controller.py
- plugins/ida_binsync/ida_binsync/hooks.py
- plugins/ida_binsync/ida_binsync/ui/info_panel.py
- plugins/ida_binsync/ida_binsync/ui/info_tables/func_info_table.py
- plugins/ida_binsync/ida_binsync/ui/info_tables/struct_info_table.py
- plugins/ida_binsync/ida_binsync/ui/info_tables/user_info_table.py
- plugins/ida_binsync/ida_binsync/ui/sync_menu.py
- setup.py
Closes #42, #38, #36, #35 
Yeah, this was a massive update.
> IDA UI Fixes and Addition

- plugins/ida_binsync/ida_binsync/controller.py
- plugins/ida_binsync/ida_binsync/hooks.py
- plugins/ida_binsync/ida_binsync/ui/info_tables/func_info_table.py
- plugins/ida_binsync/ida_binsync/ui/info_tables/struct_info_table.py
- plugins/ida_binsync/ida_binsync/ui/info_tables/user_info_table.py
Closes #41 
* added more reliability for info tables if a pull fails
> fixed comment syncing

- plugins/ida_binsync/ida_binsync/hooks.py
- bug in global comments being renamed
> fix bug found by @zachsez

- binsync/common/controller.py
- binsync/common/ui/config_dialog.py
- binsync/common/ui/control_panel.py
- binsync/common/ui/tables/activiy_table.py
- binsync/common/ui/tables/ctx_table.py
- binsync/common/ui/tables/functions_table.py
- binsync/common/ui/tables/globals_table.py
- plugins/angr_binsync/controller.py
Changes:
- Added status bar to replace old connection status label (which has been removed)
- Updated config dialog to no longer allow "__root__" as a username
- Added indicator to status bar to show what the current context is (symbol@addr)
- Fixed the file dialog being finnicky when running as a SNAP package (e.g. in pycharm)
> Angr management UI fixes

- binsync/loggercfg.py
Should hopefully fix accidentally murdering existing logging systems.
> Fix root logger murdering angr-management (and others)

- binsync/data/func.py
- plugins/ida_binsync/ida_binsync/compat.py
- plugins/ida_binsync/ida_binsync/controller.py
- plugins/ida_binsync/ida_binsync/hooks.py
> IDA Function Header Support (with custom types) 

- binsync/__init__.py
- binsync/common/controller.py
- binsync/common/ui/tables/globals_table.py
- binsync/data/__init__.py
- binsync/data/artifact.py
- binsync/data/enum.py
- binsync/data/global_variable.py
- binsync/data/stack_variable.py
- binsync/state.py
- plugins/ida_binsync/ida_binsync/compat.py
- plugins/ida_binsync/ida_binsync/controller.py
- plugins/ida_binsync/ida_binsync/hooks.py
Full support for syncing up and down for Global Variables. Partial support for syncing down enums. 
closes #49, #64
> [WIP] Global Variable & Enum Support

- plugins/ida_binsync/ida_binsync/compat.py
- plugins/ida_binsync/ida_binsync/controller.py
- plugins/ida_binsync/ida_binsync/hooks.py
> fixed structs getting no flag when unresolvable size is passed

- binsync/common/controller.py
- binsync/data/func.py
- binsync/data/stack_variable.py
- plugins/angr_binsync/controller.py
- plugins/binja_binsync/controller.py
- plugins/ida_binsync/ida_binsync/controller.py
- tests/test_state.py
- now the default syncing mechanic will be to not overwrite a users changes (yay)! With the new-coming settings table from @frqmod you should be able to select between overwrite-only and non-conflict syncing.
> Feat: Non-overwrite Syncing

- binsync/state.py
- plugins/ida_binsync/ida_binsync/controller.py
> fixed fill_struct for ida

- binsync/client.py
- plugins/angr_binsync/binsync_plugin.py
- plugins/angr_binsync/controller.py
- plugins/binja_binsync/binja_binsync.py
- plugins/binja_binsync/controller.py
> Binja & angr Stability Update

- plugins/angr_binsync/binsync_plugin.py
- plugins/angr_binsync/controller.py
> add angr-management support for goto_address (#134)

- binsync/__init__.py
- binsync/common/ui/panel_tabs/activity_table.py
- binsync/common/ui/panel_tabs/functions_table.py
- binsync/common/ui/panel_tabs/globals_table.py
- binsync/core/__init__.py
- binsync/core/client.py
- binsync/core/state.py
- binsync/data/__init__.py
- binsync/data/state.py
- binsync/merge.py
- tests/test_state.py
> Decouple State from Client

- binsync/common/controller.py
- binsync/core/client.py
- plugins/angr_binsync/controller.py
- plugins/binja_binsync/controller.py
- plugins/ida_binsync/ida_binsync/compat.py
- plugins/ida_binsync/ida_binsync/controller.py
- plugins/ida_binsync/ida_binsync/hooks.py
- plugins/ida_binsync/ida_binsync/plugin.py
> Force Push Backend

- .github/workflows/python-package-gui.yml
- README.md
- binsync/__init__.py
- binsync/common/__init__.py
- binsync/common/artifact_lifter.py
- binsync/common/controller.py
- binsync/data/__init__.py
- binsync/data/comment.py
- binsync/data/enum.py
- binsync/data/func.py
- binsync/data/global_variable.py
- binsync/data/patch.py
- binsync/data/state.py
- binsync/data/struct.py
- binsync/data/type_parser.py
- install.sh
- plugins/angr_binsync/artifact_lifter.py
- plugins/angr_binsync/controller.py
- plugins/binja_binsync/artifact_lifter.py
- plugins/binja_binsync/controller.py
- plugins/ida_binsync/ida_binsync/artifact_lifter.py
- plugins/ida_binsync/ida_binsync/controller.py
- setup.py
The long-awaited PR that addresses #125. 
- introduce better strings for Artifact type and all its children
- introduce a new lifter for all artifacts called ArtifactLifter
- introduce a new c-like type parser based on sim_types from angr
> Major Update: Artifact Lifter

- binsync/common/ui/control_panel.py
- binsync/common/ui/force_push/panels/functions_table.py
- binsync/common/ui/force_push/panels/global_panel.py
- binsync/common/ui/panel_tabs/activity_table.py
- binsync/common/ui/panel_tabs/ctx_table.py
- binsync/common/ui/panel_tabs/functions_table.py
- binsync/common/ui/panel_tabs/globals_table.py
- plugins/ida_binsync/ida_binsync/compat.py
- plugins/ida_binsync/ida_binsync/plugin.py
- Fixed the bug where rows were duplicated when selecting unselecting.
- Fixed a bug in force push displaying bad segment functions
> Fix bug with force push select all, general UI improvements

- binsync/common/controller.py
- binsync/common/ui/control_panel.py
- binsync/common/ui/force_push/panels/functions_table.py
- binsync/common/ui/force_push/panels/global_panel.py
> Force push context

- binsync/common/controller.py
- binsync/data/state.py
- binsync/data/struct.py
- plugins/angr_binsync/controller.py
- plugins/binja_binsync/controller.py
- plugins/ghidra_binsync/ghidra_binsync/controller.py
- plugins/ida_binsync/ida_binsync/controller.py
Checking time of last sync from an artifact compared to its most recent update time to decide if syncing is needed
closes #137
> Refactor filler interface for structs

- binsync/common/artifact_lifter.py
- binsync/common/controller.py
- binsync/data/artifact.py
- binsync/data/comment.py
- binsync/data/func.py
- binsync/data/stack_variable.py
- binsync/data/state.py
- binsync/data/struct.py
- binsync/data/type_parser.py
- plugins/angr_binsync/artifact_lifter.py
- plugins/angr_binsync/controller.py
- plugins/binja_binsync/artifact_lifter.py
- plugins/binja_binsync/binja_binsync.py
- plugins/binja_binsync/controller.py
- plugins/ghidra_binsync/ghidra_binsync/controller.py
- plugins/ida_binsync/ida_binsync/artifact_lifter.py
- plugins/ida_binsync/ida_binsync/compat.py
- plugins/ida_binsync/ida_binsync/controller.py
- plugins/ida_binsync/ida_binsync/hooks.py
- tests/test_state.py
> Refactor Fill

- binsync/common/controller.py
- binsync/core/client.py
> Always update even when no remote is present! 

- binsync/common/ui/config_dialog.py
- binsync/data/configuration.py
- plugins/binja_binsync/controller.py
- plugins/ghidra_binsync/ghidra_binsync/controller.py
> fix an error when the path of the binary is no longer accurate

- binsync/common/controller.py
- binsync/common/ui/force_push/panels/global_panel.py
- binsync/common/ui/panel_tabs/globals_table.py
- binsync/data/artifact.py
- binsync/data/comment.py
- binsync/data/enum.py
- binsync/data/func.py
- binsync/data/state.py
- binsync/data/struct.py
- plugins/ida_binsync/ida_binsync/compat.py
- plugins/ida_binsync/ida_binsync/controller.py
- plugins/ida_binsync/ida_binsync/hooks.py
> Add enum support to ida

- binsync/common/ui/panel_tabs/functions_table.py
- tests/test_angr_gui.py
> Speed up table maybe

- binsync/__init__.py
- binsync/common/ui/config_dialog.py
- binsync/data/configuration.py
- tests/test_angr_gui.py
Closes #188 and closes #189 while making it clearer what is configurable in the panel.
> Fix and Update Config Saving

- plugins/ghidra_binsync/artifact_lifter.py
- plugins/ghidra_binsync/control_panel_window.py
- plugins/ghidra_binsync/controller.py
- plugins/ghidra_binsync/ghidra_client.py
> Support Ghidra Return Types & Common API 

- binsync/__init__.py
- setup.cfg
Fixes: https://github.com/binsync/binsync/issues/224
> Added missing dependency

- binsync/__init__.py
- plugins/binja_binsync/binja_binsync.py
- plugins/binja_binsync/compat.py
- plugins/binja_binsync/controller.py
- plugins/binja_binsync/plugin.json
- plugins/ida_binsync/ida_binsync/controller.py
> Added support for Structs callbacks, reading, and writing in Binja

- binsync/__init__.py
- binsync/data/configuration.py
- binsync/installer.py
- setup.cfg
Closes #210, fixes bugs found in https://github.com/mahaloz/DAILA/issues/10
> Fix installer for Windows, save things to the global config

- binsync/common/controller.py
- binsync/core/client.py
- binsync/core/scheduler.py
- plugins/angr_binsync/controller.py
- plugins/binja_binsync/controller.py
- plugins/ida_binsync/ida_binsync/compat.py
- plugins/ida_binsync/ida_binsync/controller.py
> Fix IDA crashes

- binsync/__init__.py
- plugins/ida_binsync/ida_binsync/compat.py
- plugins/ida_binsync/ida_binsync/controller.py
> Hotfix for IDA crashing on special struct gcc_va_list

- binsync/__init__.py
- binsync/common/controller.py
- binsync/common/ui/config_dialog.py
- binsync/common/ui/qt_objects.py
- binsync/common/ui/utils.py
- binsync/core/client.py
- binsync/data/configuration.py
- binsync/decompilers/angr/plugin.py
- binsync/decompilers/binja/binja_binsync.py
- binsync/decompilers/ghidra/server/control_panel_window.py
- binsync/decompilers/ida/compat.py
- binsync/decompilers/ida/plugin.py
- tests/test_angr_gui.py
> Refactor Configuration UI

- binsync/__init__.py
- binsync/core/cache.py
- binsync/core/client.py
> Remove caching that can return None

- binsync/__init__.py
- binsync/common/controller.py
- binsync/installer.py
- decompiler_stubs/angr_binsync/__init__.py
- decompiler_stubs/binja_binsync/__init__.py
- decompiler_stubs/ghidra_binsync.py
- decompiler_stubs/ida_binsync.py
> Prefer copy installation from now because new stubs

- binsync/__init__.py
- binsync/decompilers/angr/control_panel_view.py
- binsync/decompilers/angr/controller.py
- setup.cfg
- tests/test_angr_gui.py
> Fix CI for new AM update

- binsync/common/ui/force_push/panels/functions_table.py
- binsync/common/ui/force_push/panels/global_panel.py
- binsync/decompilers/binja/binja_binsync.py
- binsync/decompilers/binja/compat.py
- binsync/decompilers/binja/controller.py
This is a draft to add support for GlobalVars and Enums to Binja.
Closes #255
> Add support for globalvars & enums to binja

- binsync/__init__.py
- binsync/api/controller.py
- binsync/decompilers/ghidra/client/src/main/java/binsync/BSGhidraServerAPI.java
- binsync/decompilers/ghidra/server/controller.py
- binsync/decompilers/ghidra/server/ghidra_client.py
> Standardize API for decompiling

- .github/workflows/release.yml
- binsync/__init__.py
- binsync/ui/version.py
- setup.cfg
closes #286, which is due to an error of Installing PySide6
> Revert default PySide to 2

- binsync/ui/config_dialog.py
> Fix non-selected filepath for dialog bug

- binsync/__init__.py
- binsync/decompiler_stubs/angr_binsync/__init__.py
- binsync/decompiler_stubs/binja_binsync/__init__.py
- binsync/decompiler_stubs/binja_binsync/plugin.json
- binsync/decompiler_stubs/binja_binsync/requirements.txt
- binsync/decompiler_stubs/ghidra_binsync.py
- binsync/decompiler_stubs/ida_binsync.py
- binsync/decompilers/binja/binja_binsync.py
- binsync/decompilers/binja/compat.py
> Fix linear update bugs in bn

- binsync/__init__.py
- binsync/decompilers/binja/binja_binsync.py
> Fix bad enum use in Binja

- binsync/__init__.py
- binsync/core/client.py
- binsync/decompiler_stubs/binja_binsync/plugin.json
- binsync/decompiler_stubs/binja_binsync/requirements.txt
- binsync/decompilers/binja/binja_binsync.py
> Fix a bug in Binja using a non-str convertable object

- binsync/decompilers/binja/controller.py
- binsync/ui/force_push/panels/globals_table.py
> Fix several type-related mistakes in the Binary Ninja controller

- binsync/core/client.py
- binsync/core/scheduler.py
- binsync/data/state.py
- tests/test_client.py
> Fix BinSync deleting data when it encounters corrupt state

- binsync/__init__.py
- binsync/decompilers/binja/compat.py
> Fix binja rename error

- .github/workflows/core-tests.yml
- .github/workflows/gui-tests.yml
- README.md
> Update README and CI for 3.8>= support 

- binsync/controller.py
- binsync/core/client.py
- binsync/core/state.py
- pyproject.toml
- tests/test_state.py
Closes #374 
- Depends on https://github.com/binsync/libbs/pull/69 but also changes the format of BinSync databases again :(
- Linked to: https://github.com/binsync/libbs/issues/70
> Support for Artifact formatting (JSON)

- binsync/interface_overrides/angr.py
Fixes #381 by changing the control panel dock to an auto-hiding version by default to get it out of the way a bit, this hides the close button by default (can be reverted by clicking the little pin to make it persistent). In addition, the flags `DockWidgetDeleteOnClose `and `AutoHideHasCloseButton` are set to false. Once closed the control panel can be recovered with the menu option.
> Fix control panel not being reopenable once closed

- .github/workflows/core-tests.yml
- .github/workflows/release.yml
- README.md
- pyproject.toml
> Raise min version to 3.10

- binsync/__init__.py
- binsync/controller.py
- binsync/core/client.py
- binsync/core/state.py
- binsync/interface_overrides/angr.py
- binsync/interface_overrides/ida.py
- binsync/ui/panel_tabs/util_panel.py
- binsync/ui/progress_graph/progress_window.py
- binsync/ui/progress_graph/summarize.py
- binsync/ui/progress_window.py
- pyproject.toml
- tests/ci/setup_gui_ci.sh
- tests/test_angr_gui.py
- tests/test_state.py
- an explored call-graph (shows only funcs which have been explored or are children of it) 
- hotness is total changes on the function 
- progress tracker
> Feature: Team Progress Visualizer & Deprecate last_change metadata 

- binsync/__init__.py
- binsync/controller.py
- pyproject.toml
Fixes #417 
Edit struct syncing logic when syncing all to prevent issues with nested structures.
> Fix Nested Struct Issues

- binsync/ui/config_dialog.py
This pull request extends the Remote URL text box to the Open BS Project dialog, which allows for automatic cloning of the repository to the directory noted by Project Path.
> Join to remote

- binsync/__init__.py
- binsync/interface_overrides/binja.py
- binsync/stub_files/plugin.json
- pyproject.toml
> Fix a binja startup bug

- binsync/__init__.py
- binsync/controller.py
- binsync/stub_files/plugin.json
- binsync/ui/panel_tabs/ctx_table.py
- binsync/ui/panel_tabs/functions_table.py
- binsync/ui/panel_tabs/table_model.py
- pyproject.toml
> Features: preview merges by @julietteraubolt

- binsync/core/client.py
Attempts to drastically speed up loading large binsync states by parsing directly from a filesystem instead of using the git tree.
> Change State Parsing

- binsync/core/client.py
- binsync/ui/progress_graph/progress_window.py
Small patches to client and progress view UI to avoid errors with pygraphviz while on Windows
> Patch for pygraphviz to work in Windows
